### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Pie-Not-Lie** [Enchanted-Games/falling-block-particles#2]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Mod needs updated to work with 1.21

**Describe alternatives you've considered**
N/A

**Additional context**
Love the mod, just wondered if you had any plans to update. Thanks!

**Comment by Enchanted-Games** [comment]
I will soon, just been a little busy updating my other stuff :)

**Comment by Enchanted-Games** [comment]
updated it, turns out it was easier than i thought it would be to update

**Comment by Pie-Not-Lie** [comment]
Amazing, thanks so much! :D
